
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Bank_WebService", targetNamespace = "http://bank_webservice.bank.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankWebService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://bank_webservice.bank.ws/", className = "proxy.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://bank_webservice.bank.ws/", className = "proxy.GetAccountsResponse")
    @Action(input = "http://bank_webservice.bank.ws/Bank_WebService/getAccountsRequest", output = "http://bank_webservice.bank.ws/Bank_WebService/getAccountsResponse")
    public List<Account> getAccounts();

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convertir")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convertir", targetNamespace = "http://bank_webservice.bank.ws/", className = "proxy.Convertir")
    @ResponseWrapper(localName = "ConvertirResponse", targetNamespace = "http://bank_webservice.bank.ws/", className = "proxy.ConvertirResponse")
    @Action(input = "http://bank_webservice.bank.ws/Bank_WebService/ConvertirRequest", output = "http://bank_webservice.bank.ws/Bank_WebService/ConvertirResponse")
    public double convertir(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://bank_webservice.bank.ws/", className = "proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://bank_webservice.bank.ws/", className = "proxy.GetAccountResponse")
    @Action(input = "http://bank_webservice.bank.ws/Bank_WebService/getAccountRequest", output = "http://bank_webservice.bank.ws/Bank_WebService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

}
